# Generated by Django 3.0.6 on 2020-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='message_answers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrape',
            name='message_questions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrape',
            name='message_reviews',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrape',
            name='status_answers',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Completed'), (3, 'Failed'), (2, 'Scrapping'), (1, 'Waiting')], default=1),
        ),
        migrations.AddField(
            model_name='scrape',
            name='status_questions',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Completed'), (3, 'Failed'), (2, 'Scrapping'), (1, 'Waiting')], default=1),
        ),
        migrations.AddField(
            model_name='scrape',
            name='status_reviews',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Completed'), (3, 'Failed'), (2, 'Scrapping'), (1, 'Waiting')], default=1),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Completed'), (3, 'Failed'), (2, 'Scrapping'), (1, 'Waiting')], default=1),
        ),
    ]
